### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rizkytegar** [ciptagrahasoftware/Next-Typescript-Bootstrap#1]
- [ ] Install Next.JS
- [ ] Using TypeScript in Next.JS
- [ ] Using Bootstrap in Next.JS
- [ ] Next.JS Components
- [ ] Next.JS Layouts
- [ ] Push To Github
